### ISSUE TITLE
Sonarr null exception

### ISSUE THREAD

**Issue by jedipunk** [flmorg/cleanuperr#7]
I have 14 files in my Sonar queue (port 8989) which matches the number of items reported by Cleanuperr. 

However, I use delay profiles and two download clients. So, the items in my queue may not be released or may have been released to the usenet download client.

I think either of these issues may cause a null exception when nothing is found in qBittorrent. (Unless it is caused by passing a user/pass when I don't have one for localhost. I think this would be an error somewhere else in the code, though.)

[cleanuperr.log](https://github.com/user-attachments/files/17820971/cleanuperr.log)

**Comment by Flaminel** [comment]
I've just released v1.2.2 which should have fixed this issue. Thank you for bringing this to my attention! Please let me know if anything else is crashing.

**Comment by Flaminel** [comment]
I forgot to mention that the issue was a mistake on my part, as this case was already handled in the queue cleaner. Given that you were not actually downloading anything yet, the download id in Sonarr's queue was empty, which caused the content blocker to crash when searching for an empty torrent hash.

**Comment by Flaminel** [comment]
> Unless it is caused by passing a user/pass when I don't have one for localhost

You can now pass empty instead of dummy credentials. Be sure to update to v1.2.4 for that.
